/*  pl-dma-driver.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/cdev.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("pl-dma-driver - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "pl-dma"
#define READ_OFFSET 4

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0x42611783;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

static int pl_dma_dev_open(struct inode *inode, struct file *file);
static ssize_t pl_dma_dev_read(struct file* file, char __user* buff, size_t count, loff_t* ppos);
static ssize_t pl_dma_dev_write(struct file* file, const char __user* buff, size_t count, loff_t* ppos);

struct pl_dma_driver_local {
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
    size_t size;

	struct device *device;
	struct cdev cdev;
	dev_t devid;
	struct class *class;
	void *private_data;
};

static const struct file_operations driver_fops = {
	.owner = THIS_MODULE,
	.open  = pl_dma_dev_open,
    .read  = pl_dma_dev_read,
    .write = pl_dma_dev_write,
};

static int pl_dma_dev_open(struct inode *inode, struct file *file)
{
    struct pl_dma_driver_local* lp;

    lp = container_of(inode->i_cdev, struct pl_dma_driver_local, cdev);
    file->private_data = lp;

	return 0;
}

static ssize_t pl_dma_dev_read(struct file* file, char __user* buff, size_t count, loff_t* ppos)
{
    struct pl_dma_driver_local* lp = file->private_data;
    size_t xfer_size;
    size_t remain_size;

    if (*ppos >= lp->size)
    {
        printk(KERN_ERR "offset is over mem size.\n");
		return 0;
	}
	
    xfer_size = (*ppos + count >= lp->size) ? lp->size - *ppos : count;
    if ((remain_size = copy_to_user(buff, lp->base_addr+READ_OFFSET, xfer_size)) != 0)
    {
        printk(KERN_ERR "copy_to_user() failed.\n");
		return 0;
    }

    *ppos += xfer_size;
    return xfer_size;
}

static ssize_t pl_dma_dev_write(struct file* file, const char __user* buff, size_t count, loff_t* ppos)
{
    struct pl_dma_driver_local* lp = file->private_data;
    size_t xfer_size;
    size_t remain_size;

    if (*ppos >= lp->size)
    {
        printk(KERN_ERR "offset is over mem size.\n");
		return 0;
	}

    xfer_size = (*ppos + count >= lp->size) ? lp->size - *ppos : count;

    if ((remain_size = copy_from_user(lp->base_addr, buff, xfer_size)) != 0)
    {
        printk(KERN_ERR "copy_from_user() failed.\n");
		return 0;
    }

    *ppos += xfer_size;
    return xfer_size;
}

static int pl_dma_driver_probe(struct platform_device *pdev)
{
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct pl_dma_driver_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct pl_dma_driver_local *) kmalloc(sizeof(struct pl_dma_driver_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate pl-dma-driver device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;
    lp->size = (size_t)resource_size(r_mem);

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "pl-dma-driver: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	dev_info(dev,"pl-dma-driver at 0x%08x mapped to 0x%08x(%x)\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		(unsigned int __force)lp->size);

	alloc_chrdev_region(&lp->devid, 0, 1, DRIVER_NAME);
    cdev_init(&lp->cdev, &driver_fops);
    rc = cdev_add(&lp->cdev, lp->devid, 1);

	if (rc) {
		printk ("cdev_add() failed\n");
		goto error2;
	}

    lp->class = class_create(THIS_MODULE, DRIVER_NAME);
    if(IS_ERR(lp->class))
    {
        return PTR_ERR(lp->class);
    }

    lp->device = device_create(lp->class, NULL, lp->devid, NULL, DRIVER_NAME);
    if(IS_ERR(lp->device))
    {
        return PTR_ERR(lp->device);
    }

	printk("Char device %s can be accessed through /dev! \n", DRIVER_NAME);

	return 0;

error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int pl_dma_driver_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct pl_dma_driver_local *lp = dev_get_drvdata(dev);

	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);

	cdev_del(&lp->cdev);
	device_destroy(lp->class, lp->devid);
	class_destroy(lp->class);

	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id pl_dma_driver_of_match[] = {
	{ .compatible = "liscotech,pl-dma", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, pl_dma_driver_of_match);
#else
# define pl_dma_driver_of_match
#endif


static struct platform_driver pl_dma_driver_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= pl_dma_driver_of_match,
	},
	.probe		= pl_dma_driver_probe,
	.remove		= pl_dma_driver_remove,
};

static int __init pl_dma_driver_init(void)
{
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	return platform_driver_register(&pl_dma_driver_driver);
}


static void __exit pl_dma_driver_exit(void)
{
	platform_driver_unregister(&pl_dma_driver_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(pl_dma_driver_init);
module_exit(pl_dma_driver_exit);
