/*  mbox.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/cdev.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("mbox - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "mbox"
#define READ_OFFSET 		0x08
#define STATUS_OFFSET 		0x10
#define MBOX_IS_EMPTY		0x00000001
#define MBOX_IS_FULL		0x00000002

#define SELF_TEST

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct mbox_driver_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
	char *name;

    size_t size;
	struct device *device;
	struct cdev cdev;
	dev_t devid;
	struct class *class;
	void *private_data;
};

static int mbox_dev_open(struct inode *inode, struct file *file);
static ssize_t mbox_dev_read(struct file* file, char __user* buff, size_t count, loff_t* ppos);
static ssize_t mbox_dev_write(struct file* file, const char __user* buff, size_t count, loff_t* ppos);

static irqreturn_t mbox_irq(int irq, void *lp)
{
	printk("mbox interrupt\n");
	return IRQ_HANDLED;
}

static const struct file_operations driver_fops = {
	.owner = THIS_MODULE,
	.open  = mbox_dev_open,
    .read  = mbox_dev_read,
    .write = mbox_dev_write,
};

static int mbox_dev_open(struct inode *inode, struct file *file)
{
    struct mbox_driver_local* lp;

    lp = container_of(inode->i_cdev, struct mbox_driver_local, cdev);
    file->private_data = lp;

	return 0;
}

static ssize_t mbox_dev_read(struct file* file, char __user* buff, size_t count, loff_t* ppos)
{
    struct mbox_driver_local* lp = file->private_data;
    size_t xfer_size = 0;
    //uint32_t data;

	while(count)
	{
		if(ioread32(lp->base_addr+STATUS_OFFSET) & MBOX_IS_EMPTY)
			break;

		//data = ioread32(lp->base_addr+READ_OFFSET)
		if (copy_to_user(buff+xfer_size, lp->base_addr+READ_OFFSET, 4) != 0)
		{
			printk(KERN_ERR "copy_to_user() failed.\n");
			return 0;
		}
		xfer_size += 4;
		count -= 4;
	}
	

    *ppos += xfer_size;
    return xfer_size;
}

static ssize_t mbox_dev_write(struct file* file, const char __user* buff, size_t count, loff_t* ppos)
{
    struct mbox_driver_local* lp = file->private_data;
    size_t xfer_size;
    size_t remain_size;

	while(count)
	{
		if(ioread32(lp->base_addr+STATUS_OFFSET) & MBOX_IS_FULL)
			break;

		if (copy_from_user(lp->base_addr, buff+xfer_size, 4) != 0)
		{
			printk(KERN_ERR "copy_to_user() failed.\n");
			return 0;
		}
		xfer_size += 4;
		count -= 4;
	}

    *ppos += xfer_size;
    return xfer_size;
}

#ifdef SELF_TEST
static int test_prepare(struct platform_device *pdev)
{
	struct resource *r_mem; /* IO mem resources */
	void __iomem *base_addr;
	int rc = 0;

	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 1);
	if (!r_mem) {
		printk("invalid address\n");
		return -ENODEV;
	}

	if (!request_mem_region(r_mem->start,
				r_mem->end - r_mem->start + 1,
				DRIVER_NAME)) {
		printk("Couldn't lock memory region at %p\n",
			(void *)r_mem->start);
		rc = -EBUSY;
	}

	base_addr = ioremap(r_mem->start, r_mem->end - r_mem->start + 1);
	if (!base_addr) {
		printk("mbox: Could not allocate iomem\n");
		rc = -EIO;
	}

	iowrite32(0x12345678, base_addr);
	iowrite32(0x9abcdef0, base_addr);
	release_mem_region(r_mem->start, r_mem->end - r_mem->start + 1);	
	
	return rc;
}
#endif

static int mbox_probe(struct platform_device *pdev)
{
	struct device_node *node = pdev->dev.of_node;
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct mbox_driver_local *lp = NULL;
	const char *dt_name;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct mbox_driver_local *) kmalloc(sizeof(struct mbox_driver_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate mbox device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;
    lp->size = (size_t)resource_size(r_mem);

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "mbox: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	if (!of_property_read_string(node, "mbox-name", &dt_name))
		lp->name = devm_kstrdup(&pdev->dev, dt_name, GFP_KERNEL);
	else
		lp->name = devm_kasprintf(&pdev->dev, GFP_KERNEL,
								"%pOFn", node);
								
	dev_info(dev, "--mbox name = %s\n", lp->name);
#ifdef USE_INTERRUPT
	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "mbox at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &mbox_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"mbox at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
#endif
	dev_info(dev,"mbox at 0x%08x mapped to 0x%08x\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr);

	alloc_chrdev_region(&lp->devid, 0, 1, lp->name);
    cdev_init(&lp->cdev, &driver_fops);
    rc = cdev_add(&lp->cdev, lp->devid, 1);

	if (rc) {
		printk ("cdev_add() failed\n");
		goto error2;
	}

    lp->class = class_create(THIS_MODULE, lp->name);
    if(IS_ERR(lp->class))
    {
		printk ("class_create() failed\n");
		release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
		kfree(lp);
		dev_set_drvdata(dev, NULL);
        return PTR_ERR(lp->class);
    }

    lp->device = device_create(lp->class, NULL, lp->devid, NULL, lp->name);
    if(IS_ERR(lp->device))
    {
		printk ("device_create() failed\n");
		release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
		kfree(lp);
		dev_set_drvdata(dev, NULL);
        return PTR_ERR(lp->device);
    }

	printk("Char device %s can be accessed through /dev! \n", lp->name);
#ifdef SELF_TEST
{
	uint32_t status;
	test_prepare(pdev);
	
	status = ioread32(lp->base_addr+STATUS_OFFSET);	
	printk("mbox: status %x\n");
#if 0	
	uint32_t data1, data2, 
	status = ioread32(lp->base_addr+STATUS_OFFSET);	
	data1 = ioread32(lp->base_addr+READ_OFFSET);	
	data2 = ioread32(lp->base_addr+READ_OFFSET);	
	status1 = ioread32(lp->base_addr+STATUS_OFFSET);	

	printk("self test: %x %x %x %x\n", status, data1, data2, status1);
#endif
}	
#endif


	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int mbox_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct mbox_driver_local *lp = dev_get_drvdata(dev);
	
    cdev_del(&lp->cdev);
    printk("chrdev unregister\n");
    
    unregister_chrdev_region(lp->devid, 1);
    
    /* 3. destroy device */
    device_destroy(lp->class, lp->devid);
    
    /* 4. dectroy class */
    class_destroy(lp->class);
#ifdef USE_INTERRUPT
	free_irq(lp->irq, lp);
#endif
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id mbox_of_match[] = {
	{ .compatible = "liscotech,mbox", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, mbox_of_match);
#else
# define mbox_of_match
#endif


static struct platform_driver mbox_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= mbox_of_match,
	},
	.probe		= mbox_probe,
	.remove		= mbox_remove,
};

static int __init mbox_init(void)
{
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	return platform_driver_register(&mbox_driver);
}


static void __exit mbox_exit(void)
{
	platform_driver_unregister(&mbox_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(mbox_init);
module_exit(mbox_exit);
